### ISSUE TITLE
instructions? 

### ISSUE THREAD

**Issue by tashchuk23** [led23UP/gameFramework_Domino#1]
GUI looks nice, but help button does nothing and there was no instructions for how to play the game. No idea what the objective is or how to score points, or how to win.

Also not sure why the board gets reset when you run out of dominos

good game!  just needs instructions

**Comment by benning23** [comment]
We don't know how to play the game and therefore don't know if the resetting of the board is suppose to happen or how the point system works (Why does the com keep winning?)
