### ISSUE TITLE
GUI Issues

### ISSUE THREAD

**Issue by JenniferBrana** [led23UP/gameFramework_Domino#5]
We found that the dominos were not placed correctly. The photo below shows how when we placed a 6 that should have connected to a 6 it placed it upsidedown. 
![unnamed](https://user-images.githubusercontent.com/67402276/140808851-757a51e5-11fa-4122-be33-21020c2e6ee1.jpg)

**Comment by Paul352** [comment]
This issue has been fixed. Dominoes now line up correctly when placed.
